
# Site settings
title: 
email:
description: > # this means to ignore newlines until "baseurl:"
  
baseurl:  # the subpath of your site, e.g. /blog/
url:https://lacarreraecologica.github.io/  # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
gems: [jekyll-paginate]

markdown: kramdown
# toc_levels: 1..2
